repos:
  - repo: local
    hooks:
      - id: task-lint
        name: task lint
        entry: task lint
        language: system
        pass_filenames: false
      - id: task-test
        name: task test
        entry: task test
        language: system
        pass_filenames: false
      - id: task-render
        name: task render
        entry: task render
        language: system
        pass_filenames: false
      - id: task-brew-validate
        name: task brew:validate
        entry: task brew:validate
        language: system
        pass_filenames: false
