#!/usr/bin/env zsh

## CORE MODULES ##
zmodule input
zmodule termtitle
zmodule utility
zmodule ssh

## UTILITY AND TOOLS ##
zmodule fzf
zmodule kiesman99/zim-zoxide
zmodule direnv
zmodule joke/zim-starship

## COMPLETION AND SYNTAX ##
zmodule zsh-users/zsh-completions --fpath src
zmodule completion
zmodule zsh-users/zsh-autosuggestions
zmodule zdharma-continuum/fast-syntax-highlighting
