#!/usr/bin/env zsh
# shellcheck disable=all

unsetopt GLOBAL_RCS    # Prevent sourcing of global Zsh config files (e.g., /etc/zshrc)
skip_global_compinit=1

export LC_ALL="${LC_ALL:-en_US.UTF-8}"
export LANG="${LANG:-en_US.UTF-8}"
export LANGUAGE="${LANGUAGE:-en_US.UTF-8}"
