---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.local"]

- link:
    ~/.gitconfig: files/gitconfig
    ~/.gitignore_global: files/gitignore_global
    ~/.hushlogin: /dev/null
    ~/.zsh: files/zsh
    ~/.zshrc: files/zshrc
    ~/.dir_colors: files/dir_colors

- shell:
  - [antibody bundle < ~/.zsh/plugins.txt > ~/.zsh/plugins.zsh, Installing zsh plugins]
