---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.local"]

- link:
    ~/.bash_logout: /dev/null
    ~/.bash_profile: files/bash_profile
    ~/.bashrc: files/bashrc
    ~/.gitconfig: files/gitconfig
    ~/.gitignore_global: files/gitignore_global
    ~/.hushlogin: /dev/null
    ~/.profile: /dev/null
    ~/.creds: /Volumes/Secure/creds
    ~/.ssh: /Volumes/Secure/ssh
