---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.local"]

- link:
    ~/.bash_logout: /dev/null
    ~/.bash_profile: files/bash_profile
    ~/.bashrc: files/bashrc
    ~/.dir_colors: files/dir_colors
    ~/.hushlogin: /dev/null
    ~/.gitconfig: files/gitconfig
    ~/.gitignore_global: files/gitignore_global
