---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- link:
    ~/.dir_colors: files/dir_colors
    ~/.gitconfig: files/gitconfig
    ~/.gitignore_global: files/gitignore_global
    ~/.hushlogin: /dev/null
    ~/.zsh: files/zsh
    ~/.zshrc: files/zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
