---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.local"]

- link:
    ~/.gitconfig: files/gitconfig
    ~/.gitignore_global: files/gitignore_global
    ~/.hushlogin: /dev/null
    ~/.zsh: files/zsh
    ~/.zshrc: files/zshrc
