---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.local"]

- link:
    ~/.dir_colors: files/dir_colors
    ~/.config/nvim: files/nvim
    ~/.local/build: files/build
    ~/.xinitrc: files/xinitrc
    ~/.Xresources: files/Xresources

- shell:
    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv || true
    - git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv || true
    - git clone https://github.com/momo-lab/xxenv-latest.git ~/.pyenv/plugins/xxenv-latest || true
    - git clone https://github.com/tfutils/tfenv.git ~/.tfenv || true
