---
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config"]

- link:
    ~/.dir_colors: files/dir_colors
    ~/.tmux.conf: files/tmux.conf
    ~/.config/nvim: files/nvim

- shell:
    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv || true
    - git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv || true
    - git clone https://github.com/momo-lab/xxenv-latest.git ~/.pyenv/plugins/xxenv-latest || true
    - git clone https://github.com/tfutils/tfenv.git ~/.tfenv || true
