# Console apps
brew "ansible"
brew "ansible-lint"
brew "aria2"
brew "asciinema"
brew "glide"
brew "gnupg"
brew "go"
brew "go-delve/delve/delve"
brew "jq"
brew "ripgrep"
brew "shellcheck"
brew "ssh-copy-id"
brew "wrk"
brew "zplug"

# GUI apps
cask "adapter"
cask "adobe-dng-converter"
cask "alfred"
cask "atom"
cask "bartender"
cask "calibre"
cask "cleanmymac"
cask "docker"
cask "firefox"
cask "go2shell"
cask "google-chrome"
cask "handbrake"
cask "iterm2"
cask "minikube"
cask "skype"
cask "sourcetree"
cask "steermouse"
cask "telegram-desktop"
cask "transmission"
cask "vagrant"
cask "virtualbox"
cask "viscosity"
cask "vlc"

# App Store Apps
mas "1Password", id: 443987910
mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "The Unarchiver", id: 425424353
mas "Transmit", id: 403388562
mas "iMovie", id: 408981434
