#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# basic setup
# -----------------------------------------------------------------------------
# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# set locale
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

# -----------------------------------------------------------------------------
# bash options
# -----------------------------------------------------------------------------
shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend
shopt -s direxpand
shopt -s dirspell

bind 'set colored-completion-prefix on'
bind 'set colored-stats on'
bind 'set completion-ignore-case on'
bind 'set completion-query-items 200'
bind 'set mark-symlinked-directories on'
bind 'set page-completions off'
bind 'set show-all-if-ambiguous on'
bind 'set skip-completed-text on'
bind 'set visible-stats on'
bind 'set enable-keypad on'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

HISTCONTROL="erasedups:ignoreboth"
HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear:update"
HISTFILESIZE="100000"
HISTSIZE="${HISTFILESIZE}"

# bash prompt
PS1='[\u \W]\$ '

# additional local paths
export PATH="/usr/local/bin:/usr/local/sbin:${PATH}"

# pager
export PAGER="less"
export LESS="FRX"

# ls colors
export LSCOLORS="ExGxFxdaCxDaDahbadacec"

# aliases
alias grep="grep --color --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.git --exclude-dir=.bzr --exclude-dir=CVS --binary-files=without-match"
alias ls="ls -FGh"

function update() {
    brew update
    brew upgrade
    brew cask outdated | xargs brew cask reinstall
    mas upgrade
    brew cleanup -s
}

function setenv() {
    case $1 in
    proxy)
        local _proxy="http://***REMOVED***:3128"
        export http_proxy="${_proxy}"
        export https_proxy="${_proxy}"
        export HTTP_PROXY="${_proxy}"
        export HTTPS_PROXY="${_proxy}"
        export ALL_PROXY="${_proxy}"
        ;;
    -proxy)
        unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY
        ;;
    creds)
        export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/.creds/gcp/jenkins.json"
        export creds_google="$(cat ${GOOGLE_APPLICATION_CREDENTIALS})"
        export creds_aws="$(cat ${HOME}/.creds/aws/credit.json)"
        export creds_bluecat="$(cat ${HOME}/.creds/bluecat.b64)"

        ;;
    -creds)
        unset GOOGLE_APPLICATION_CREDENTIALS
        ;;
    pynossl)
        export PYTHONHTTPSVERIFY="0"
        ;;
    -pynossl)
        unset PYTHONHTTPSVERIFY
        ;;
    *)
        echo "Need to specify which env varibles to set"
        ;;
    esac
}

# -----------------------------------------------------------------------------
# tools
# -----------------------------------------------------------------------------
# fzf
if command -v fzf 1>/dev/null 2>&1; then
    export FZF_DEFAULT_OPTS="--inline-info --layout=reverse --height 10 --color=dark --color=fg:#abb2bf,bg:#282c34,hl:#5c6370,fg+:#abb2bf,bg+:#2c323c,hl+:#c678dd,info:#e5c07b,prompt:#c678dd,pointer:#c678dd,marker:#e06c75,spinner:#c678dd,header:#5c6370"
    if command -v fd &>/dev/null; then
        export FZF_DEFAULT_COMMAND="fd . ${HOME}"
        export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
        export FZF_ALT_C_COMMAND="fd -t d . ${HOME}"
    fi
    export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
    source "$(brew --prefix)/opt/fzf/shell/key-bindings.bash"
fi

# go
if command -v go 1>/dev/null 2>&1; then
    export GOPATH="${HOME}/.go"
    export PATH="${GOPATH}/bin:${PATH}"
fi

# -----------------------------------------------------------------------------
# additional path manipulation
# -----------------------------------------------------------------------------
# includes user's private bin if it exists
[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:${PATH}"

# remove duplicate path entries
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
