#!/bin/zsh

# macos clean and load path
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# path: go
if hash go 2>/dev/null; then
  export GOPATH="$HOME/Documents/Projects/go"
  echo $PATH | grep -q $GOPATH/bin || export PATH=$GOPATH/bin:$PATH
fi
