#!/usr/local/env zsh

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# macos clean and load path
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# additional local paths
export PATH="/usr/local/bin:/usr/local/sbin:${PATH}"

# include user's homebrew bin if it exists
[[ -d "${HOME}/.brew/bin" ]] && export PATH="${HOME}/.brew/bin:${PATH}"

# includes user's private bin if it exists
[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:${PATH}"

# plugins
source ~/.zsh/plugins.zsh

# config
source ~/.zsh/env.zsh
source ~/.zsh/options.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/keybindings.zsh
source ~/.zsh/post.zsh
