#!/bin/zsh

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# plugins
source ~/.zsh/plugins.zsh

# config
source ~/.zsh/options.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/keybindings.zsh
source ~/.zsh/env.zsh
#source ~/.zsh/windowtitle.zsh
