"$schema" = 'https://starship.rs/config-schema.json'

# Minimal, fast, and colorful prompt with essential info

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$jobs\
$character"""

add_newline = false

##############################################################################
# User and Host
##############################################################################

[username]
format = '[$user]($style)'
show_always = true
style_root = "#e78284"    # Red
style_user = "#e5c890"    # Yellow

[hostname]
format = "[@](#737994)[$hostname]($style)"  # Overlay0
style = "#a6d189"        # Green

##############################################################################
# Directory
##############################################################################

[directory]
format = "[:](#737994)[$path]($style)[$read_only]($read_only_style) "
style = "#8caaee"        # Blue

##############################################################################
# Git Information
##############################################################################

[git_branch]
format = "[$branch]($style)"
style = "#e78284"        # Red

[git_status]
ahead = "⇡"
behind = "⇣"
conflicted = "="
deleted = "x"
diverged = "⇕"
format = '([\[](#737994)[$all_status$ahead_behind]($style)[\]](#737994)) '
modified = "!"
renamed = ">"
staged = "+"
stashed = "\\$"
style = "#81c8be"        # Teal
untracked = "?"
up_to_date = ""

[git_state]
style = "#e78284"        # Red

##############################################################################
# Command Duration
##############################################################################

[cmd_duration]
format = "[$duration]($style) "
style = "#e5c890"        # Yellow

##############################################################################
# Jobs Indicator
##############################################################################

[jobs]
symbol = "✦"
style = "#737994"        # Overlay0
format = "[$symbol$number]($style) "

##############################################################################
# Prompt Character
##############################################################################

[character]
error_symbol = "[❯](#e78284)"       # Red
success_symbol = "[❯](#ca9ee6)"     # Mauve
vicmd_symbol = "[❮](#a6d189)"       # Green
