"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$character"""

add_newline = false

[username]
format = '[$user]($style)'
show_always = true
style_root = "red"
style_user = "yellow"

[hostname]
format = "[@](bright-black)[$hostname]($style)"
style = "green"

[directory]
format = "[:](bright-black)[$path]($style)[$read_only]($read_only_style) "
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "red"

[git_status]
ahead = "⇡"
behind = "⇣"
conflicted = "="
deleted = "x"
diverged = "⇕"
format = '([\[](bright-black)[$all_status$ahead_behind]($style)[\]](bright-black)) '
modified = "!"
renamed = ">"
staged = "+"
stashed = "\\$"
style = "cyan"
untracked = "?"
up_to_date = ""

[git_state]
style = "red"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](purple)"
vicmd_symbol = "[❮](green)"
