"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$character"""

add_newline = false

[username]
format = '[$user]($style)'
show_always = true
style_root = "red"
style_user = "yellow"

[hostname]
format = "[@](bright-black)[$hostname]($style)"
style = "peach"

[directory]
format = "[:](bright-black)[$path]($style)[$read_only]($read_only_style) "
style = "lavender"

[git_branch]
format = "[$branch]($style)"
style = "mauve"

[git_status]
ahead = "⇡"
behind = "⇣"
conflicted = "="
deleted = "x"
diverged = "⇕"
format = '([\[](bright-black)[$all_status$ahead_behind]($style)[\]](bright-black)) '
modified = "!"
renamed = ">"
staged = "+"
stashed = "\\$"
style = "cyan"
untracked = "?"
up_to_date = ""

[git_state]
style = "red"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](purple)"
vicmd_symbol = "[❮](green)"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
