min_version = "2026.9.0"

[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["go", "node", "erlang", "elixir", "opentofu"]

[tools]
go = "prefix:1.27"
node = "prefix:26"
erlang = "prefix:29"
elixir = "prefix:1.20"
bitwarden = "prefix:2026.8"
prettier = "prefix:3.9"
opentofu = "prefix:1.12"
